### ISSUE TITLE
roibuddy startup script fails on OS X (MacPorts Python)

### ISSUE THREAD

**Issue by neurodroid** [losonczylab/roibuddy#12]
The roibuddy startup script that gets installed into Python's `bin` directory fails when roibuddy is installed with pip on MacPorts Python 2.7. I've tested the installation on 3 Macs by now, and on each of them I had to apply the following patch to make it work:

``` diff
--- a/roibuddy  2015-03-24 23:32:41.000000000 +0000
+++ b/roibuddy  2015-03-24 23:31:27.000000000 +0000
@@ -4,7 +4,7 @@
 import re
 import sys

-from roibuddy.roi_buddy import main
+from ROIBuddy.roi_buddy import main

 if __name__ == '__main__':
     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
```

Strangely this is not required on Linux systems.

**Comment by pkaifosh** [comment]
Thanks for the report! Can you confirm that this patch does does not the installation on Linux systems?

**Comment by neurodroid** [comment]
This patch breaks roibuddy on Linux. _With_ this patch, on a Linux system I get:

``` python
Traceback (most recent call last):
  File "/home/pacmen/virtualenv-2.7/bin/roibuddy", line 7, in <module>
    from ROIBuddy.roi_buddy import main
  File "/home/pacmen/virtualenv-2.7/local/lib/python2.7/site-packages/ROIBuddy/roi_buddy.py", line 44, in <module>
    from pudb import set_trace
ImportError: No module named pudb
```

On MacPorts Python 2.7 _without_ this patch I get:

``` python
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/roibuddy", line 7, in <module>
    from roibuddy.roi_buddy import main
ImportError: No module named roibuddy.roi_buddy
```

**Comment by pkaifosh** [comment]
OK. It looks like someone left in a pudb reference from some debugging efforts. Perhaps once that import is removed, then the same approach should work for both Linux & MacOSX.

@jzaremba @nbdanielson Can you look into this? Thanks!

**Comment by jzaremba** [comment]
Yeah, we use pudb for debugging, so it must have been accidentally left in at some point. I don't see it in either branch now, you should just be able to delete that line.  We've intentionally left the pudb import within the debug_trace function, but that should be the only place its found.

**Comment by pkaifosh** [comment]
Is this all fixed and working now?

**Comment by neurodroid** [comment]
roibuddy @387b472 starts up without any issues on OS X and linux.
